### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by RadAd** [RadAd/RMVirtualDesktop#1]
It appears the GUIDs for Windows 11 are different:

https://github.com/Ciantic/VirtualDesktopAccessor/issues/51

**Comment by Philip-Hel** [comment]
Guids + additional methods and multiple monitor support.
My fork the dll mostly works with win11.

**Comment by RadAd** [comment]
Im still on windows 10, unable to upgrade to 11 yet, so I will keep mine as is for now. 

It would be great to support both at the same time but it seems that that could only be achieved by duplicating the code for each version.

**Comment by RadAd** [comment]
I have added support for Windows 11.

I have tested it on Windows 10, still seems to work.

I haven't tested it on Windows 11 yet.

**Comment by RadAd** [comment]
As of version 22H2 (Build 22621.819):
The virtual desktop interfaces are no longer mentioned in the registry. Without knowing at least the GUIDs of these interfaces I am no longer able to support Windows 11.

**Comment by RadAd** [comment]
I've tested it on Windows 11 22H2. Seems to work ok now.
