### ISSUE TITLE
Rainmeter crash after enabling this plugin

### ISSUE THREAD

**Issue by is-sam** [RadAd/RMVirtualDesktop#2]
Hi,

After enabling this plugin on Windows 11, the whole Rainmeter app crashed and I couldn't open it anymore.

I had to go to AppData/Roaming/Rainmeter and edit the config file to manually remove the VirtualDesktop plugin.

**Comment by RadAd** [comment]
Microsoft has taken extra lengths in Windows 11 22H2 to hide the virtual desktop interfaces. Without this information, I can no longer support Windows 11.

**Comment by RadAd** [comment]
I've tested it on Windows 11 22H2. Seems to work ok now. Try v1.3.
